/*
Catapult REST Endpoints

OpenAPI Specification of catapult-rest

API version: 1.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Mosaic type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Mosaic{}

// Mosaic struct for Mosaic
type Mosaic struct {
	// Mosaic identifier.
	Id string `json:"id"`
	// Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
	Amount string `json:"amount"`
}

type _Mosaic Mosaic

// NewMosaic instantiates a new Mosaic object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMosaic(id string, amount string) *Mosaic {
	this := Mosaic{}
	this.Id = id
	this.Amount = amount
	return &this
}

// NewMosaicWithDefaults instantiates a new Mosaic object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMosaicWithDefaults() *Mosaic {
	this := Mosaic{}
	return &this
}

// GetId returns the Id field value
func (o *Mosaic) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Mosaic) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Mosaic) SetId(v string) {
	o.Id = v
}

// GetAmount returns the Amount field value
func (o *Mosaic) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *Mosaic) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *Mosaic) SetAmount(v string) {
	o.Amount = v
}

func (o Mosaic) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Mosaic) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *Mosaic) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMosaic := _Mosaic{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMosaic)

	if err != nil {
		return err
	}

	*o = Mosaic(varMosaic)

	return err
}

type NullableMosaic struct {
	value *Mosaic
	isSet bool
}

func (v NullableMosaic) Get() *Mosaic {
	return v.value
}

func (v *NullableMosaic) Set(val *Mosaic) {
	v.value = val
	v.isSet = true
}

func (v NullableMosaic) IsSet() bool {
	return v.isSet
}

func (v *NullableMosaic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMosaic(val *Mosaic) *NullableMosaic {
	return &NullableMosaic{value: val, isSet: true}
}

func (v NullableMosaic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMosaic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


