/*
Catapult REST Endpoints

OpenAPI Specification of catapult-rest

API version: 1.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmbeddedVotingKeyLinkTransactionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddedVotingKeyLinkTransactionDTO{}

// EmbeddedVotingKeyLinkTransactionDTO struct for EmbeddedVotingKeyLinkTransactionDTO
type EmbeddedVotingKeyLinkTransactionDTO struct {
	// Public key.
	SignerPublicKey string `json:"signerPublicKey"`
	// Entity version.
	Version int32 `json:"version"`
	Network NetworkTypeEnum `json:"network"`
	Type int32 `json:"type"`
	// 32 bytes voting public key.
	LinkedPublicKey string `json:"linkedPublicKey"`
	// Finalization Epoch
	StartEpoch int64 `json:"startEpoch"`
	// Finalization Epoch
	EndEpoch int64 `json:"endEpoch"`
	LinkAction LinkActionEnum `json:"linkAction"`
}

type _EmbeddedVotingKeyLinkTransactionDTO EmbeddedVotingKeyLinkTransactionDTO

// NewEmbeddedVotingKeyLinkTransactionDTO instantiates a new EmbeddedVotingKeyLinkTransactionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedVotingKeyLinkTransactionDTO(signerPublicKey string, version int32, network NetworkTypeEnum, type_ int32, linkedPublicKey string, startEpoch int64, endEpoch int64, linkAction LinkActionEnum) *EmbeddedVotingKeyLinkTransactionDTO {
	this := EmbeddedVotingKeyLinkTransactionDTO{}
	this.SignerPublicKey = signerPublicKey
	this.Version = version
	this.Network = network
	this.Type = type_
	this.LinkedPublicKey = linkedPublicKey
	this.StartEpoch = startEpoch
	this.EndEpoch = endEpoch
	this.LinkAction = linkAction
	return &this
}

// NewEmbeddedVotingKeyLinkTransactionDTOWithDefaults instantiates a new EmbeddedVotingKeyLinkTransactionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedVotingKeyLinkTransactionDTOWithDefaults() *EmbeddedVotingKeyLinkTransactionDTO {
	this := EmbeddedVotingKeyLinkTransactionDTO{}
	return &this
}

// GetSignerPublicKey returns the SignerPublicKey field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetSignerPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignerPublicKey
}

// GetSignerPublicKeyOk returns a tuple with the SignerPublicKey field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetSignerPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignerPublicKey, true
}

// SetSignerPublicKey sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetSignerPublicKey(v string) {
	o.SignerPublicKey = v
}

// GetVersion returns the Version field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetVersion(v int32) {
	o.Version = v
}

// GetNetwork returns the Network field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetNetwork() NetworkTypeEnum {
	if o == nil {
		var ret NetworkTypeEnum
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetNetworkOk() (*NetworkTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetNetwork(v NetworkTypeEnum) {
	o.Network = v
}

// GetType returns the Type field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetType(v int32) {
	o.Type = v
}

// GetLinkedPublicKey returns the LinkedPublicKey field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetLinkedPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LinkedPublicKey
}

// GetLinkedPublicKeyOk returns a tuple with the LinkedPublicKey field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetLinkedPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkedPublicKey, true
}

// SetLinkedPublicKey sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetLinkedPublicKey(v string) {
	o.LinkedPublicKey = v
}

// GetStartEpoch returns the StartEpoch field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetStartEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.StartEpoch
}

// GetStartEpochOk returns a tuple with the StartEpoch field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetStartEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartEpoch, true
}

// SetStartEpoch sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetStartEpoch(v int64) {
	o.StartEpoch = v
}

// GetEndEpoch returns the EndEpoch field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetEndEpoch() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.EndEpoch
}

// GetEndEpochOk returns a tuple with the EndEpoch field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetEndEpochOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndEpoch, true
}

// SetEndEpoch sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetEndEpoch(v int64) {
	o.EndEpoch = v
}

// GetLinkAction returns the LinkAction field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetLinkAction() LinkActionEnum {
	if o == nil {
		var ret LinkActionEnum
		return ret
	}

	return o.LinkAction
}

// GetLinkActionOk returns a tuple with the LinkAction field value
// and a boolean to check if the value has been set.
func (o *EmbeddedVotingKeyLinkTransactionDTO) GetLinkActionOk() (*LinkActionEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LinkAction, true
}

// SetLinkAction sets field value
func (o *EmbeddedVotingKeyLinkTransactionDTO) SetLinkAction(v LinkActionEnum) {
	o.LinkAction = v
}

func (o EmbeddedVotingKeyLinkTransactionDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddedVotingKeyLinkTransactionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signerPublicKey"] = o.SignerPublicKey
	toSerialize["version"] = o.Version
	toSerialize["network"] = o.Network
	toSerialize["type"] = o.Type
	toSerialize["linkedPublicKey"] = o.LinkedPublicKey
	toSerialize["startEpoch"] = o.StartEpoch
	toSerialize["endEpoch"] = o.EndEpoch
	toSerialize["linkAction"] = o.LinkAction
	return toSerialize, nil
}

func (o *EmbeddedVotingKeyLinkTransactionDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signerPublicKey",
		"version",
		"network",
		"type",
		"linkedPublicKey",
		"startEpoch",
		"endEpoch",
		"linkAction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmbeddedVotingKeyLinkTransactionDTO := _EmbeddedVotingKeyLinkTransactionDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmbeddedVotingKeyLinkTransactionDTO)

	if err != nil {
		return err
	}

	*o = EmbeddedVotingKeyLinkTransactionDTO(varEmbeddedVotingKeyLinkTransactionDTO)

	return err
}

type NullableEmbeddedVotingKeyLinkTransactionDTO struct {
	value *EmbeddedVotingKeyLinkTransactionDTO
	isSet bool
}

func (v NullableEmbeddedVotingKeyLinkTransactionDTO) Get() *EmbeddedVotingKeyLinkTransactionDTO {
	return v.value
}

func (v *NullableEmbeddedVotingKeyLinkTransactionDTO) Set(val *EmbeddedVotingKeyLinkTransactionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedVotingKeyLinkTransactionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedVotingKeyLinkTransactionDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedVotingKeyLinkTransactionDTO(val *EmbeddedVotingKeyLinkTransactionDTO) *NullableEmbeddedVotingKeyLinkTransactionDTO {
	return &NullableEmbeddedVotingKeyLinkTransactionDTO{value: val, isSet: true}
}

func (v NullableEmbeddedVotingKeyLinkTransactionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedVotingKeyLinkTransactionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


