/*
Catapult REST Endpoints

OpenAPI Specification of catapult-rest

API version: 1.0.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmbeddedMosaicGlobalRestrictionTransactionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmbeddedMosaicGlobalRestrictionTransactionDTO{}

// EmbeddedMosaicGlobalRestrictionTransactionDTO struct for EmbeddedMosaicGlobalRestrictionTransactionDTO
type EmbeddedMosaicGlobalRestrictionTransactionDTO struct {
	// Public key.
	SignerPublicKey string `json:"signerPublicKey"`
	// Entity version.
	Version int32 `json:"version"`
	Network NetworkTypeEnum `json:"network"`
	Type int32 `json:"type"`
	// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
	MosaicId string `json:"mosaicId"`
	// Mosaic identifier. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of the real mosaic identifier. 
	ReferenceMosaicId string `json:"referenceMosaicId"`
	// Restriction key.
	RestrictionKey string `json:"restrictionKey"`
	// Restriction value.
	PreviousRestrictionValue string `json:"previousRestrictionValue"`
	// Restriction value.
	NewRestrictionValue string `json:"newRestrictionValue"`
	PreviousRestrictionType MosaicRestrictionTypeEnum `json:"previousRestrictionType"`
	NewRestrictionType MosaicRestrictionTypeEnum `json:"newRestrictionType"`
}

type _EmbeddedMosaicGlobalRestrictionTransactionDTO EmbeddedMosaicGlobalRestrictionTransactionDTO

// NewEmbeddedMosaicGlobalRestrictionTransactionDTO instantiates a new EmbeddedMosaicGlobalRestrictionTransactionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmbeddedMosaicGlobalRestrictionTransactionDTO(signerPublicKey string, version int32, network NetworkTypeEnum, type_ int32, mosaicId string, referenceMosaicId string, restrictionKey string, previousRestrictionValue string, newRestrictionValue string, previousRestrictionType MosaicRestrictionTypeEnum, newRestrictionType MosaicRestrictionTypeEnum) *EmbeddedMosaicGlobalRestrictionTransactionDTO {
	this := EmbeddedMosaicGlobalRestrictionTransactionDTO{}
	this.SignerPublicKey = signerPublicKey
	this.Version = version
	this.Network = network
	this.Type = type_
	this.MosaicId = mosaicId
	this.ReferenceMosaicId = referenceMosaicId
	this.RestrictionKey = restrictionKey
	this.PreviousRestrictionValue = previousRestrictionValue
	this.NewRestrictionValue = newRestrictionValue
	this.PreviousRestrictionType = previousRestrictionType
	this.NewRestrictionType = newRestrictionType
	return &this
}

// NewEmbeddedMosaicGlobalRestrictionTransactionDTOWithDefaults instantiates a new EmbeddedMosaicGlobalRestrictionTransactionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmbeddedMosaicGlobalRestrictionTransactionDTOWithDefaults() *EmbeddedMosaicGlobalRestrictionTransactionDTO {
	this := EmbeddedMosaicGlobalRestrictionTransactionDTO{}
	return &this
}

// GetSignerPublicKey returns the SignerPublicKey field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetSignerPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignerPublicKey
}

// GetSignerPublicKeyOk returns a tuple with the SignerPublicKey field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetSignerPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignerPublicKey, true
}

// SetSignerPublicKey sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetSignerPublicKey(v string) {
	o.SignerPublicKey = v
}

// GetVersion returns the Version field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetVersion(v int32) {
	o.Version = v
}

// GetNetwork returns the Network field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNetwork() NetworkTypeEnum {
	if o == nil {
		var ret NetworkTypeEnum
		return ret
	}

	return o.Network
}

// GetNetworkOk returns a tuple with the Network field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNetworkOk() (*NetworkTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Network, true
}

// SetNetwork sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetNetwork(v NetworkTypeEnum) {
	o.Network = v
}

// GetType returns the Type field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetType() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetType(v int32) {
	o.Type = v
}

// GetMosaicId returns the MosaicId field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetMosaicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MosaicId
}

// GetMosaicIdOk returns a tuple with the MosaicId field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetMosaicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MosaicId, true
}

// SetMosaicId sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetMosaicId(v string) {
	o.MosaicId = v
}

// GetReferenceMosaicId returns the ReferenceMosaicId field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetReferenceMosaicId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReferenceMosaicId
}

// GetReferenceMosaicIdOk returns a tuple with the ReferenceMosaicId field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetReferenceMosaicIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReferenceMosaicId, true
}

// SetReferenceMosaicId sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetReferenceMosaicId(v string) {
	o.ReferenceMosaicId = v
}

// GetRestrictionKey returns the RestrictionKey field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetRestrictionKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RestrictionKey
}

// GetRestrictionKeyOk returns a tuple with the RestrictionKey field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetRestrictionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestrictionKey, true
}

// SetRestrictionKey sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetRestrictionKey(v string) {
	o.RestrictionKey = v
}

// GetPreviousRestrictionValue returns the PreviousRestrictionValue field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetPreviousRestrictionValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreviousRestrictionValue
}

// GetPreviousRestrictionValueOk returns a tuple with the PreviousRestrictionValue field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetPreviousRestrictionValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousRestrictionValue, true
}

// SetPreviousRestrictionValue sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetPreviousRestrictionValue(v string) {
	o.PreviousRestrictionValue = v
}

// GetNewRestrictionValue returns the NewRestrictionValue field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNewRestrictionValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NewRestrictionValue
}

// GetNewRestrictionValueOk returns a tuple with the NewRestrictionValue field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNewRestrictionValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewRestrictionValue, true
}

// SetNewRestrictionValue sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetNewRestrictionValue(v string) {
	o.NewRestrictionValue = v
}

// GetPreviousRestrictionType returns the PreviousRestrictionType field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetPreviousRestrictionType() MosaicRestrictionTypeEnum {
	if o == nil {
		var ret MosaicRestrictionTypeEnum
		return ret
	}

	return o.PreviousRestrictionType
}

// GetPreviousRestrictionTypeOk returns a tuple with the PreviousRestrictionType field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetPreviousRestrictionTypeOk() (*MosaicRestrictionTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreviousRestrictionType, true
}

// SetPreviousRestrictionType sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetPreviousRestrictionType(v MosaicRestrictionTypeEnum) {
	o.PreviousRestrictionType = v
}

// GetNewRestrictionType returns the NewRestrictionType field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNewRestrictionType() MosaicRestrictionTypeEnum {
	if o == nil {
		var ret MosaicRestrictionTypeEnum
		return ret
	}

	return o.NewRestrictionType
}

// GetNewRestrictionTypeOk returns a tuple with the NewRestrictionType field value
// and a boolean to check if the value has been set.
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) GetNewRestrictionTypeOk() (*MosaicRestrictionTypeEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NewRestrictionType, true
}

// SetNewRestrictionType sets field value
func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) SetNewRestrictionType(v MosaicRestrictionTypeEnum) {
	o.NewRestrictionType = v
}

func (o EmbeddedMosaicGlobalRestrictionTransactionDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmbeddedMosaicGlobalRestrictionTransactionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["signerPublicKey"] = o.SignerPublicKey
	toSerialize["version"] = o.Version
	toSerialize["network"] = o.Network
	toSerialize["type"] = o.Type
	toSerialize["mosaicId"] = o.MosaicId
	toSerialize["referenceMosaicId"] = o.ReferenceMosaicId
	toSerialize["restrictionKey"] = o.RestrictionKey
	toSerialize["previousRestrictionValue"] = o.PreviousRestrictionValue
	toSerialize["newRestrictionValue"] = o.NewRestrictionValue
	toSerialize["previousRestrictionType"] = o.PreviousRestrictionType
	toSerialize["newRestrictionType"] = o.NewRestrictionType
	return toSerialize, nil
}

func (o *EmbeddedMosaicGlobalRestrictionTransactionDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signerPublicKey",
		"version",
		"network",
		"type",
		"mosaicId",
		"referenceMosaicId",
		"restrictionKey",
		"previousRestrictionValue",
		"newRestrictionValue",
		"previousRestrictionType",
		"newRestrictionType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmbeddedMosaicGlobalRestrictionTransactionDTO := _EmbeddedMosaicGlobalRestrictionTransactionDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmbeddedMosaicGlobalRestrictionTransactionDTO)

	if err != nil {
		return err
	}

	*o = EmbeddedMosaicGlobalRestrictionTransactionDTO(varEmbeddedMosaicGlobalRestrictionTransactionDTO)

	return err
}

type NullableEmbeddedMosaicGlobalRestrictionTransactionDTO struct {
	value *EmbeddedMosaicGlobalRestrictionTransactionDTO
	isSet bool
}

func (v NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) Get() *EmbeddedMosaicGlobalRestrictionTransactionDTO {
	return v.value
}

func (v *NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) Set(val *EmbeddedMosaicGlobalRestrictionTransactionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmbeddedMosaicGlobalRestrictionTransactionDTO(val *EmbeddedMosaicGlobalRestrictionTransactionDTO) *NullableEmbeddedMosaicGlobalRestrictionTransactionDTO {
	return &NullableEmbeddedMosaicGlobalRestrictionTransactionDTO{value: val, isSet: true}
}

func (v NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmbeddedMosaicGlobalRestrictionTransactionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


