# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.node_routes_api import NodeRoutesApi


class TestNodeRoutesApi(unittest.TestCase):
    """NodeRoutesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodeRoutesApi()

    def tearDown(self) -> None:
        pass

    def test_get_node_health(self) -> None:
        """Test case for get_node_health

        Get the node health information
        """
        pass

    def test_get_node_info(self) -> None:
        """Test case for get_node_info

        Get the node information
        """
        pass

    def test_get_node_peers(self) -> None:
        """Test case for get_node_peers

        Get peers information
        """
        pass

    def test_get_node_storage(self) -> None:
        """Test case for get_node_storage

        Get the storage information of the node
        """
        pass

    def test_get_node_time(self) -> None:
        """Test case for get_node_time

        Get the node time
        """
        pass

    def test_get_server_info(self) -> None:
        """Test case for get_server_info

        Get the version of the running REST component
        """
        pass

    def test_get_unlocked_account(self) -> None:
        """Test case for get_unlocked_account

        Get the unlocked harvesting account public keys.
        """
        pass


if __name__ == '__main__':
    unittest.main()
