# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.merkle_path_item_dto import MerklePathItemDTO

class TestMerklePathItemDTO(unittest.TestCase):
    """MerklePathItemDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerklePathItemDTO:
        """Test MerklePathItemDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerklePathItemDTO`
        """
        model = MerklePathItemDTO()
        if include_optional:
            return MerklePathItemDTO(
                position = 'left',
                hash = 'C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810'
            )
        else:
            return MerklePathItemDTO(
        )
        """

    def testMerklePathItemDTO(self):
        """Test MerklePathItemDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
