# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mosaic_supply_change_transaction_body_dto import MosaicSupplyChangeTransactionBodyDTO

class TestMosaicSupplyChangeTransactionBodyDTO(unittest.TestCase):
    """MosaicSupplyChangeTransactionBodyDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MosaicSupplyChangeTransactionBodyDTO:
        """Test MosaicSupplyChangeTransactionBodyDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MosaicSupplyChangeTransactionBodyDTO`
        """
        model = MosaicSupplyChangeTransactionBodyDTO()
        if include_optional:
            return MosaicSupplyChangeTransactionBodyDTO(
                mosaic_id = '85BBEA6CC462B244',
                delta = '123456',
                action = 0
            )
        else:
            return MosaicSupplyChangeTransactionBodyDTO(
                mosaic_id = '85BBEA6CC462B244',
                delta = '123456',
                action = 0,
        )
        """

    def testMosaicSupplyChangeTransactionBodyDTO(self):
        """Test MosaicSupplyChangeTransactionBodyDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
