# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.multisig_routes_api import MultisigRoutesApi


class TestMultisigRoutesApi(unittest.TestCase):
    """MultisigRoutesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MultisigRoutesApi()

    def tearDown(self) -> None:
        pass

    def test_get_account_multisig(self) -> None:
        """Test case for get_account_multisig

        Get multisig account information
        """
        pass

    def test_get_account_multisig_graph(self) -> None:
        """Test case for get_account_multisig_graph

        Get multisig account graph information
        """
        pass

    def test_get_account_multisig_merkle(self) -> None:
        """Test case for get_account_multisig_merkle

        Get multisig account merkle information
        """
        pass


if __name__ == '__main__':
    unittest.main()
