# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.mosaic_restriction_dto import MosaicRestrictionDTO

class TestMosaicRestrictionDTO(unittest.TestCase):
    """MosaicRestrictionDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MosaicRestrictionDTO:
        """Test MosaicRestrictionDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MosaicRestrictionDTO`
        """
        model = MosaicRestrictionDTO()
        if include_optional:
            return MosaicRestrictionDTO(
                id = '',
                mosaic_restriction_entry = openapi_client.models.mosaic_global_restriction_entry_wrapper_dto.MosaicGlobalRestrictionEntryWrapperDTO(
                    version = 1, 
                    composite_hash = 'C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810', 
                    entry_type = 0, 
                    mosaic_id = '0DC67FBE1CAD29E3', 
                    restrictions = [
                        openapi_client.models.mosaic_global_restriction_entry_dto.MosaicGlobalRestrictionEntryDTO(
                            key = '0DC67FBE1CAD29E3', 
                            restriction = openapi_client.models.mosaic_global_restriction_entry_restriction_dto.MosaicGlobalRestrictionEntryRestrictionDTO(
                                reference_mosaic_id = '0DC67FBE1CAD29E3', 
                                restriction_value = '1000', 
                                restriction_type = 0, ), )
                        ], )
            )
        else:
            return MosaicRestrictionDTO(
                id = '',
                mosaic_restriction_entry = openapi_client.models.mosaic_global_restriction_entry_wrapper_dto.MosaicGlobalRestrictionEntryWrapperDTO(
                    version = 1, 
                    composite_hash = 'C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810', 
                    entry_type = 0, 
                    mosaic_id = '0DC67FBE1CAD29E3', 
                    restrictions = [
                        openapi_client.models.mosaic_global_restriction_entry_dto.MosaicGlobalRestrictionEntryDTO(
                            key = '0DC67FBE1CAD29E3', 
                            restriction = openapi_client.models.mosaic_global_restriction_entry_restriction_dto.MosaicGlobalRestrictionEntryRestrictionDTO(
                                reference_mosaic_id = '0DC67FBE1CAD29E3', 
                                restriction_value = '1000', 
                                restriction_type = 0, ), )
                        ], ),
        )
        """

    def testMosaicRestrictionDTO(self):
        """Test MosaicRestrictionDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
