# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.secret_lock_transaction_body_dto import SecretLockTransactionBodyDTO

class TestSecretLockTransactionBodyDTO(unittest.TestCase):
    """SecretLockTransactionBodyDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecretLockTransactionBodyDTO:
        """Test SecretLockTransactionBodyDTO
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SecretLockTransactionBodyDTO`
        """
        model = SecretLockTransactionBodyDTO()
        if include_optional:
            return SecretLockTransactionBodyDTO(
                recipient_address = 'TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA',
                secret = 'C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810',
                mosaic_id = '85BBEA6CC462B244',
                amount = '123456',
                duration = '200',
                hash_algorithm = 0
            )
        else:
            return SecretLockTransactionBodyDTO(
                recipient_address = 'TAOXUJOTTW3W5XTBQMQEX3SQNA6MCUVGXLXR3TA',
                secret = 'C8FC3FB54FDDFBCE0E8C71224990124E4EEC5AD5D30E592EDFA9524669A23810',
                mosaic_id = '85BBEA6CC462B244',
                amount = '123456',
                duration = '200',
                hash_algorithm = 0,
        )
        """

    def testSecretLockTransactionBodyDTO(self):
        """Test SecretLockTransactionBodyDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
