/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.AccountIds;
import org.openapitools.client.model.AccountInfoDTO;
import org.openapitools.client.model.AccountOrderByEnum;
import org.openapitools.client.model.AccountPage;
import org.openapitools.client.model.MerkleStateInfoDTO;
import org.openapitools.client.model.ModelError;
import org.openapitools.client.model.Order;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountRoutesApi
 */
@Disabled
public class AccountRoutesApiTest {

    private final AccountRoutesApi api = new AccountRoutesApi();

    /**
     * Get account information
     *
     * Returns the account information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountInfoTest() throws ApiException {
        String accountId = null;
        AccountInfoDTO response = api.getAccountInfo(accountId);
        // TODO: test validations
    }

    /**
     * Get account merkle information
     *
     * Returns the account merkle information.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountInfoMerkleTest() throws ApiException {
        String accountId = null;
        MerkleStateInfoDTO response = api.getAccountInfoMerkle(accountId);
        // TODO: test validations
    }

    /**
     * Get accounts information
     *
     * Returns the account information for an array of accounts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAccountsInfoTest() throws ApiException {
        AccountIds accountIds = null;
        List<AccountInfoDTO> response = api.getAccountsInfo(accountIds);
        // TODO: test validations
    }

    /**
     * Search accounts
     *
     * Gets an array of accounts.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchAccountsTest() throws ApiException {
        Integer pageSize = null;
        Integer pageNumber = null;
        String offset = null;
        Order order = null;
        AccountOrderByEnum orderBy = null;
        String mosaicId = null;
        AccountPage response = api.searchAccounts(pageSize, pageNumber, offset, order, orderBy, mosaicId);
        // TODO: test validations
    }

}
