//
// NodeIdentityEqualityStrategy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Node equality strategy. Defines if the identifier for the node must be its public key or host.  */
public enum NodeIdentityEqualityStrategy: String, Codable, CaseIterable {
    case host = "host"
    case publicKey = "public-key"
}
