//
// StageEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Type of stage: * 0 - Prevote. * 1 - Precommit. * 2 - Count.  */
public enum StageEnum: Int, Codable, CaseIterable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
