/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Transaction that triggered the receipt.
    /// </summary>
    [DataContract(Name = "SourceDTO")]
    public partial class SourceDTO : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SourceDTO" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SourceDTO() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SourceDTO" /> class.
        /// </summary>
        /// <param name="primaryId">A number that allows uint 32 values. (required).</param>
        /// <param name="secondaryId">A number that allows uint 32 values. (required).</param>
        public SourceDTO(long primaryId = default(long), long secondaryId = default(long))
        {
            this.PrimaryId = primaryId;
            this.SecondaryId = secondaryId;
        }

        /// <summary>
        /// A number that allows uint 32 values.
        /// </summary>
        /// <value>A number that allows uint 32 values.</value>
        /// <example>2222212828</example>
        [DataMember(Name = "primaryId", IsRequired = true, EmitDefaultValue = true)]
        public long PrimaryId { get; set; }

        /// <summary>
        /// A number that allows uint 32 values.
        /// </summary>
        /// <value>A number that allows uint 32 values.</value>
        /// <example>2222212828</example>
        [DataMember(Name = "secondaryId", IsRequired = true, EmitDefaultValue = true)]
        public long SecondaryId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SourceDTO {\n");
            sb.Append("  PrimaryId: ").Append(PrimaryId).Append("\n");
            sb.Append("  SecondaryId: ").Append(SecondaryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
