/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountKeyLinkNetworkPropertiesDTO
 */
public class AccountKeyLinkNetworkPropertiesDTOTest {
    private final AccountKeyLinkNetworkPropertiesDTO model = new AccountKeyLinkNetworkPropertiesDTO();

    /**
     * Model tests for AccountKeyLinkNetworkPropertiesDTO
     */
    @Test
    public void testAccountKeyLinkNetworkPropertiesDTO() {
        // TODO: test AccountKeyLinkNetworkPropertiesDTO
    }

    /**
     * Test the property 'dummy'
     */
    @Test
    public void dummyTest() {
        // TODO: test dummy
    }

}
