/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountRestrictionFlagsEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountAddressRestrictionTransactionBodyDTO
 */
public class AccountAddressRestrictionTransactionBodyDTOTest {
    private final AccountAddressRestrictionTransactionBodyDTO model = new AccountAddressRestrictionTransactionBodyDTO();

    /**
     * Model tests for AccountAddressRestrictionTransactionBodyDTO
     */
    @Test
    public void testAccountAddressRestrictionTransactionBodyDTO() {
        // TODO: test AccountAddressRestrictionTransactionBodyDTO
    }

    /**
     * Test the property 'restrictionFlags'
     */
    @Test
    public void restrictionFlagsTest() {
        // TODO: test restrictionFlags
    }

    /**
     * Test the property 'restrictionAdditions'
     */
    @Test
    public void restrictionAdditionsTest() {
        // TODO: test restrictionAdditions
    }

    /**
     * Test the property 'restrictionDeletions'
     */
    @Test
    public void restrictionDeletionsTest() {
        // TODO: test restrictionDeletions
    }

}
