/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.LinkActionEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AccountKeyLinkTransactionBodyDTO
 */
public class AccountKeyLinkTransactionBodyDTOTest {
    private final AccountKeyLinkTransactionBodyDTO model = new AccountKeyLinkTransactionBodyDTO();

    /**
     * Model tests for AccountKeyLinkTransactionBodyDTO
     */
    @Test
    public void testAccountKeyLinkTransactionBodyDTO() {
        // TODO: test AccountKeyLinkTransactionBodyDTO
    }

    /**
     * Test the property 'linkedPublicKey'
     */
    @Test
    public void linkedPublicKeyTest() {
        // TODO: test linkedPublicKey
    }

    /**
     * Test the property 'linkAction'
     */
    @Test
    public void linkActionTest() {
        // TODO: test linkAction
    }

}
