/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.NetworkTypeEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddedHashLockTransactionDTO
 */
public class EmbeddedHashLockTransactionDTOTest {
    private final EmbeddedHashLockTransactionDTO model = new EmbeddedHashLockTransactionDTO();

    /**
     * Model tests for EmbeddedHashLockTransactionDTO
     */
    @Test
    public void testEmbeddedHashLockTransactionDTO() {
        // TODO: test EmbeddedHashLockTransactionDTO
    }

    /**
     * Test the property 'signerPublicKey'
     */
    @Test
    public void signerPublicKeyTest() {
        // TODO: test signerPublicKey
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'mosaicId'
     */
    @Test
    public void mosaicIdTest() {
        // TODO: test mosaicId
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'duration'
     */
    @Test
    public void durationTest() {
        // TODO: test duration
    }

    /**
     * Test the property 'hash'
     */
    @Test
    public void hashTest() {
        // TODO: test hash
    }

}
