/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.NetworkTypeEnum;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmbeddedMultisigAccountModificationTransactionDTO
 */
public class EmbeddedMultisigAccountModificationTransactionDTOTest {
    private final EmbeddedMultisigAccountModificationTransactionDTO model = new EmbeddedMultisigAccountModificationTransactionDTO();

    /**
     * Model tests for EmbeddedMultisigAccountModificationTransactionDTO
     */
    @Test
    public void testEmbeddedMultisigAccountModificationTransactionDTO() {
        // TODO: test EmbeddedMultisigAccountModificationTransactionDTO
    }

    /**
     * Test the property 'signerPublicKey'
     */
    @Test
    public void signerPublicKeyTest() {
        // TODO: test signerPublicKey
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'network'
     */
    @Test
    public void networkTest() {
        // TODO: test network
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'minRemovalDelta'
     */
    @Test
    public void minRemovalDeltaTest() {
        // TODO: test minRemovalDelta
    }

    /**
     * Test the property 'minApprovalDelta'
     */
    @Test
    public void minApprovalDeltaTest() {
        // TODO: test minApprovalDelta
    }

    /**
     * Test the property 'addressAdditions'
     */
    @Test
    public void addressAdditionsTest() {
        // TODO: test addressAdditions
    }

    /**
     * Test the property 'addressDeletions'
     */
    @Test
    public void addressDeletionsTest() {
        // TODO: test addressDeletions
    }

}
