/*
 * Catapult REST Endpoints
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.AccountNamesDTO;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * AccountsNamesDTO
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-02T22:49:20.273938+09:00[Asia/Tokyo]")
public class AccountsNamesDTO {
  public static final String SERIALIZED_NAME_ACCOUNT_NAMES = "accountNames";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAMES)
  private List<AccountNamesDTO> accountNames = new ArrayList<>();

  public AccountsNamesDTO() {
  }

  public AccountsNamesDTO accountNames(List<AccountNamesDTO> accountNames) {
    this.accountNames = accountNames;
    return this;
  }

  public AccountsNamesDTO addAccountNamesItem(AccountNamesDTO accountNamesItem) {
    if (this.accountNames == null) {
      this.accountNames = new ArrayList<>();
    }
    this.accountNames.add(accountNamesItem);
    return this;
  }

   /**
   * Array of account names.
   * @return accountNames
  **/
  @javax.annotation.Nonnull
  public List<AccountNamesDTO> getAccountNames() {
    return accountNames;
  }

  public void setAccountNames(List<AccountNamesDTO> accountNames) {
    this.accountNames = accountNames;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountsNamesDTO accountsNamesDTO = (AccountsNamesDTO) o;
    return Objects.equals(this.accountNames, accountsNamesDTO.accountNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNames);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountsNamesDTO {\n");
    sb.append("    accountNames: ").append(toIndentedString(accountNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accountNames");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accountNames");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to AccountsNamesDTO
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!AccountsNamesDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in AccountsNamesDTO is not found in the empty JSON string", AccountsNamesDTO.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!AccountsNamesDTO.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `AccountsNamesDTO` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : AccountsNamesDTO.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("accountNames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `accountNames` to be an array in the JSON string but got `%s`", jsonObj.get("accountNames").toString()));
      }

      JsonArray jsonArrayaccountNames = jsonObj.getAsJsonArray("accountNames");
      // validate the required field `accountNames` (array)
      for (int i = 0; i < jsonArrayaccountNames.size(); i++) {
        AccountNamesDTO.validateJsonElement(jsonArrayaccountNames.get(i));
      };
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!AccountsNamesDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'AccountsNamesDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<AccountsNamesDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(AccountsNamesDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<AccountsNamesDTO>() {
           @Override
           public void write(JsonWriter out, AccountsNamesDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public AccountsNamesDTO read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of AccountsNamesDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of AccountsNamesDTO
  * @throws IOException if the JSON string is invalid with respect to AccountsNamesDTO
  */
  public static AccountsNamesDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, AccountsNamesDTO.class);
  }

 /**
  * Convert an instance of AccountsNamesDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

