/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountDTO
        //private AccountDTO instance;

        public AccountDTOTests()
        {
            // TODO uncomment below to create an instance of AccountDTO
            //instance = new AccountDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountDTO
        /// </summary>
        [Fact]
        public void AccountDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountDTO
            //Assert.IsType<AccountDTO>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'AddressHeight'
        /// </summary>
        [Fact]
        public void AddressHeightTest()
        {
            // TODO unit test for the property 'AddressHeight'
        }

        /// <summary>
        /// Test the property 'PublicKey'
        /// </summary>
        [Fact]
        public void PublicKeyTest()
        {
            // TODO unit test for the property 'PublicKey'
        }

        /// <summary>
        /// Test the property 'PublicKeyHeight'
        /// </summary>
        [Fact]
        public void PublicKeyHeightTest()
        {
            // TODO unit test for the property 'PublicKeyHeight'
        }

        /// <summary>
        /// Test the property 'AccountType'
        /// </summary>
        [Fact]
        public void AccountTypeTest()
        {
            // TODO unit test for the property 'AccountType'
        }

        /// <summary>
        /// Test the property 'SupplementalPublicKeys'
        /// </summary>
        [Fact]
        public void SupplementalPublicKeysTest()
        {
            // TODO unit test for the property 'SupplementalPublicKeys'
        }

        /// <summary>
        /// Test the property 'ActivityBuckets'
        /// </summary>
        [Fact]
        public void ActivityBucketsTest()
        {
            // TODO unit test for the property 'ActivityBuckets'
        }

        /// <summary>
        /// Test the property 'Mosaics'
        /// </summary>
        [Fact]
        public void MosaicsTest()
        {
            // TODO unit test for the property 'Mosaics'
        }

        /// <summary>
        /// Test the property 'Importance'
        /// </summary>
        [Fact]
        public void ImportanceTest()
        {
            // TODO unit test for the property 'Importance'
        }

        /// <summary>
        /// Test the property 'ImportanceHeight'
        /// </summary>
        [Fact]
        public void ImportanceHeightTest()
        {
            // TODO unit test for the property 'ImportanceHeight'
        }
    }
}
