/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockInfoDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockInfoDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockInfoDTO
        //private BlockInfoDTO instance;

        public BlockInfoDTOTests()
        {
            // TODO uncomment below to create an instance of BlockInfoDTO
            //instance = new BlockInfoDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockInfoDTO
        /// </summary>
        [Fact]
        public void BlockInfoDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockInfoDTO
            //Assert.IsType<BlockInfoDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Meta'
        /// </summary>
        [Fact]
        public void MetaTest()
        {
            // TODO unit test for the property 'Meta'
        }

        /// <summary>
        /// Test the property 'Block'
        /// </summary>
        [Fact]
        public void BlockTest()
        {
            // TODO unit test for the property 'Block'
        }
    }
}
