/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing MultisigAccountModificationTransactionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultisigAccountModificationTransactionDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultisigAccountModificationTransactionDTO
        //private MultisigAccountModificationTransactionDTO instance;

        public MultisigAccountModificationTransactionDTOTests()
        {
            // TODO uncomment below to create an instance of MultisigAccountModificationTransactionDTO
            //instance = new MultisigAccountModificationTransactionDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultisigAccountModificationTransactionDTO
        /// </summary>
        [Fact]
        public void MultisigAccountModificationTransactionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultisigAccountModificationTransactionDTO
            //Assert.IsType<MultisigAccountModificationTransactionDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

        /// <summary>
        /// Test the property 'SignerPublicKey'
        /// </summary>
        [Fact]
        public void SignerPublicKeyTest()
        {
            // TODO unit test for the property 'SignerPublicKey'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'MaxFee'
        /// </summary>
        [Fact]
        public void MaxFeeTest()
        {
            // TODO unit test for the property 'MaxFee'
        }

        /// <summary>
        /// Test the property 'Deadline'
        /// </summary>
        [Fact]
        public void DeadlineTest()
        {
            // TODO unit test for the property 'Deadline'
        }

        /// <summary>
        /// Test the property 'MinRemovalDelta'
        /// </summary>
        [Fact]
        public void MinRemovalDeltaTest()
        {
            // TODO unit test for the property 'MinRemovalDelta'
        }

        /// <summary>
        /// Test the property 'MinApprovalDelta'
        /// </summary>
        [Fact]
        public void MinApprovalDeltaTest()
        {
            // TODO unit test for the property 'MinApprovalDelta'
        }

        /// <summary>
        /// Test the property 'AddressAdditions'
        /// </summary>
        [Fact]
        public void AddressAdditionsTest()
        {
            // TODO unit test for the property 'AddressAdditions'
        }

        /// <summary>
        /// Test the property 'AddressDeletions'
        /// </summary>
        [Fact]
        public void AddressDeletionsTest()
        {
            // TODO unit test for the property 'AddressDeletions'
        }
    }
}
