/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing NodeTimeDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeTimeDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeTimeDTO
        //private NodeTimeDTO instance;

        public NodeTimeDTOTests()
        {
            // TODO uncomment below to create an instance of NodeTimeDTO
            //instance = new NodeTimeDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeTimeDTO
        /// </summary>
        [Fact]
        public void NodeTimeDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeTimeDTO
            //Assert.IsType<NodeTimeDTO>(instance);
        }

        /// <summary>
        /// Test the property 'CommunicationTimestamps'
        /// </summary>
        [Fact]
        public void CommunicationTimestampsTest()
        {
            // TODO unit test for the property 'CommunicationTimestamps'
        }
    }
}
