/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing SecretLockInfoDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecretLockInfoDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecretLockInfoDTO
        //private SecretLockInfoDTO instance;

        public SecretLockInfoDTOTests()
        {
            // TODO uncomment below to create an instance of SecretLockInfoDTO
            //instance = new SecretLockInfoDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecretLockInfoDTO
        /// </summary>
        [Fact]
        public void SecretLockInfoDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecretLockInfoDTO
            //Assert.IsType<SecretLockInfoDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'VarLock'
        /// </summary>
        [Fact]
        public void VarLockTest()
        {
            // TODO unit test for the property 'VarLock'
        }
    }
}
