/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionDTO
        //private TransactionDTO instance;

        public TransactionDTOTests()
        {
            // TODO uncomment below to create an instance of TransactionDTO
            //instance = new TransactionDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionDTO
        /// </summary>
        [Fact]
        public void TransactionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionDTO
            //Assert.IsType<TransactionDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

        /// <summary>
        /// Test the property 'SignerPublicKey'
        /// </summary>
        [Fact]
        public void SignerPublicKeyTest()
        {
            // TODO unit test for the property 'SignerPublicKey'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'MaxFee'
        /// </summary>
        [Fact]
        public void MaxFeeTest()
        {
            // TODO unit test for the property 'MaxFee'
        }

        /// <summary>
        /// Test the property 'Deadline'
        /// </summary>
        [Fact]
        public void DeadlineTest()
        {
            // TODO unit test for the property 'Deadline'
        }
    }
}
