/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SymbolRestClient.Model;
using SymbolRestClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SymbolRestClient.Test.Model
{
    /// <summary>
    ///  Class for testing TransactionStatusEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransactionStatusEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransactionStatusEnum
        //private TransactionStatusEnum instance;

        public TransactionStatusEnumTests()
        {
            // TODO uncomment below to create an instance of TransactionStatusEnum
            //instance = new TransactionStatusEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransactionStatusEnum
        /// </summary>
        [Fact]
        public void TransactionStatusEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransactionStatusEnum
            //Assert.IsType<TransactionStatusEnum>(instance);
        }
    }
}
