# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.receipt_type_enum import ReceiptTypeEnum
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class BalanceTransferReceiptDTO(BaseModel):
    """
    Receipt stored when a state change that triggered a mosaic transfer.
    """ # noqa: E501
    version: StrictInt = Field(description="Version of the receipt.")
    type: ReceiptTypeEnum
    mosaic_id: StrictStr = Field(description="Mosaic identifier.", alias="mosaicId")
    amount: StrictStr = Field(description="Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).")
    sender_address: StrictStr = Field(description="Address encoded using a 32-character set.", alias="senderAddress")
    recipient_address: StrictStr = Field(description="Address encoded using a 32-character set.", alias="recipientAddress")
    __properties: ClassVar[List[str]] = ["version", "type", "mosaicId", "amount", "senderAddress", "recipientAddress"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BalanceTransferReceiptDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of BalanceTransferReceiptDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "type": obj.get("type"),
            "mosaicId": obj.get("mosaicId"),
            "amount": obj.get("amount"),
            "senderAddress": obj.get("senderAddress"),
            "recipientAddress": obj.get("recipientAddress")
        })
        return _obj


