<?php
/**
 * TransactionFeesDTO
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SymbolRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SymbolRestClient\Model;

use \ArrayAccess;
use \SymbolRestClient\ObjectSerializer;

/**
 * TransactionFeesDTO Class Doc Comment
 *
 * @category Class
 * @package  SymbolRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class TransactionFeesDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'TransactionFeesDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'average_fee_multiplier' => 'int',
        'median_fee_multiplier' => 'int',
        'highest_fee_multiplier' => 'int',
        'lowest_fee_multiplier' => 'int',
        'min_fee_multiplier' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'average_fee_multiplier' => 'int64',
        'median_fee_multiplier' => 'int64',
        'highest_fee_multiplier' => 'int64',
        'lowest_fee_multiplier' => 'int64',
        'min_fee_multiplier' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'average_fee_multiplier' => false,
        'median_fee_multiplier' => false,
        'highest_fee_multiplier' => false,
        'lowest_fee_multiplier' => false,
        'min_fee_multiplier' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'average_fee_multiplier' => 'averageFeeMultiplier',
        'median_fee_multiplier' => 'medianFeeMultiplier',
        'highest_fee_multiplier' => 'highestFeeMultiplier',
        'lowest_fee_multiplier' => 'lowestFeeMultiplier',
        'min_fee_multiplier' => 'minFeeMultiplier'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'average_fee_multiplier' => 'setAverageFeeMultiplier',
        'median_fee_multiplier' => 'setMedianFeeMultiplier',
        'highest_fee_multiplier' => 'setHighestFeeMultiplier',
        'lowest_fee_multiplier' => 'setLowestFeeMultiplier',
        'min_fee_multiplier' => 'setMinFeeMultiplier'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'average_fee_multiplier' => 'getAverageFeeMultiplier',
        'median_fee_multiplier' => 'getMedianFeeMultiplier',
        'highest_fee_multiplier' => 'getHighestFeeMultiplier',
        'lowest_fee_multiplier' => 'getLowestFeeMultiplier',
        'min_fee_multiplier' => 'getMinFeeMultiplier'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('average_fee_multiplier', $data ?? [], null);
        $this->setIfExists('median_fee_multiplier', $data ?? [], null);
        $this->setIfExists('highest_fee_multiplier', $data ?? [], null);
        $this->setIfExists('lowest_fee_multiplier', $data ?? [], null);
        $this->setIfExists('min_fee_multiplier', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['average_fee_multiplier'] === null) {
            $invalidProperties[] = "'average_fee_multiplier' can't be null";
        }
        if ($this->container['median_fee_multiplier'] === null) {
            $invalidProperties[] = "'median_fee_multiplier' can't be null";
        }
        if ($this->container['highest_fee_multiplier'] === null) {
            $invalidProperties[] = "'highest_fee_multiplier' can't be null";
        }
        if ($this->container['lowest_fee_multiplier'] === null) {
            $invalidProperties[] = "'lowest_fee_multiplier' can't be null";
        }
        if ($this->container['min_fee_multiplier'] === null) {
            $invalidProperties[] = "'min_fee_multiplier' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets average_fee_multiplier
     *
     * @return int
     */
    public function getAverageFeeMultiplier()
    {
        return $this->container['average_fee_multiplier'];
    }

    /**
     * Sets average_fee_multiplier
     *
     * @param int $average_fee_multiplier Fee multiplier applied to transactions contained in block.
     *
     * @return self
     */
    public function setAverageFeeMultiplier($average_fee_multiplier)
    {
        if (is_null($average_fee_multiplier)) {
            throw new \InvalidArgumentException('non-nullable average_fee_multiplier cannot be null');
        }
        $this->container['average_fee_multiplier'] = $average_fee_multiplier;

        return $this;
    }

    /**
     * Gets median_fee_multiplier
     *
     * @return int
     */
    public function getMedianFeeMultiplier()
    {
        return $this->container['median_fee_multiplier'];
    }

    /**
     * Sets median_fee_multiplier
     *
     * @param int $median_fee_multiplier Fee multiplier applied to transactions contained in block.
     *
     * @return self
     */
    public function setMedianFeeMultiplier($median_fee_multiplier)
    {
        if (is_null($median_fee_multiplier)) {
            throw new \InvalidArgumentException('non-nullable median_fee_multiplier cannot be null');
        }
        $this->container['median_fee_multiplier'] = $median_fee_multiplier;

        return $this;
    }

    /**
     * Gets highest_fee_multiplier
     *
     * @return int
     */
    public function getHighestFeeMultiplier()
    {
        return $this->container['highest_fee_multiplier'];
    }

    /**
     * Sets highest_fee_multiplier
     *
     * @param int $highest_fee_multiplier Fee multiplier applied to transactions contained in block.
     *
     * @return self
     */
    public function setHighestFeeMultiplier($highest_fee_multiplier)
    {
        if (is_null($highest_fee_multiplier)) {
            throw new \InvalidArgumentException('non-nullable highest_fee_multiplier cannot be null');
        }
        $this->container['highest_fee_multiplier'] = $highest_fee_multiplier;

        return $this;
    }

    /**
     * Gets lowest_fee_multiplier
     *
     * @return int
     */
    public function getLowestFeeMultiplier()
    {
        return $this->container['lowest_fee_multiplier'];
    }

    /**
     * Sets lowest_fee_multiplier
     *
     * @param int $lowest_fee_multiplier Fee multiplier applied to transactions contained in block.
     *
     * @return self
     */
    public function setLowestFeeMultiplier($lowest_fee_multiplier)
    {
        if (is_null($lowest_fee_multiplier)) {
            throw new \InvalidArgumentException('non-nullable lowest_fee_multiplier cannot be null');
        }
        $this->container['lowest_fee_multiplier'] = $lowest_fee_multiplier;

        return $this;
    }

    /**
     * Gets min_fee_multiplier
     *
     * @return int
     */
    public function getMinFeeMultiplier()
    {
        return $this->container['min_fee_multiplier'];
    }

    /**
     * Sets min_fee_multiplier
     *
     * @param int $min_fee_multiplier Fee multiplier applied to transactions contained in block.
     *
     * @return self
     */
    public function setMinFeeMultiplier($min_fee_multiplier)
    {
        if (is_null($min_fee_multiplier)) {
            throw new \InvalidArgumentException('non-nullable min_fee_multiplier cannot be null');
        }
        $this->container['min_fee_multiplier'] = $min_fee_multiplier;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


