<?php
/**
 * ReceiptRoutesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  SymbolRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SymbolRestClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SymbolRestClient\ApiException;
use SymbolRestClient\Configuration;
use SymbolRestClient\HeaderSelector;
use SymbolRestClient\ObjectSerializer;

/**
 * ReceiptRoutesApi Class Doc Comment
 *
 * @category Class
 * @package  SymbolRestClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReceiptRoutesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'searchAddressResolutionStatements' => [
            'application/json',
        ],
        'searchMosaicResolutionStatements' => [
            'application/json',
        ],
        'searchReceipts' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation searchAddressResolutionStatements
     *
     * Get receipts address resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchAddressResolutionStatements'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SymbolRestClient\Model\ResolutionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError
     */
    public function searchAddressResolutionStatements($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchAddressResolutionStatements'][0])
    {
        list($response) = $this->searchAddressResolutionStatementsWithHttpInfo($height, $page_size, $page_number, $offset, $order, $contentType);
        return $response;
    }

    /**
     * Operation searchAddressResolutionStatementsWithHttpInfo
     *
     * Get receipts address resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchAddressResolutionStatements'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SymbolRestClient\Model\ResolutionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchAddressResolutionStatementsWithHttpInfo($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchAddressResolutionStatements'][0])
    {
        $request = $this->searchAddressResolutionStatementsRequest($height, $page_size, $page_number, $offset, $order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SymbolRestClient\Model\ResolutionStatementPage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ResolutionStatementPage' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ResolutionStatementPage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SymbolRestClient\Model\ResolutionStatementPage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ResolutionStatementPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchAddressResolutionStatementsAsync
     *
     * Get receipts address resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchAddressResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAddressResolutionStatementsAsync($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchAddressResolutionStatements'][0])
    {
        return $this->searchAddressResolutionStatementsAsyncWithHttpInfo($height, $page_size, $page_number, $offset, $order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchAddressResolutionStatementsAsyncWithHttpInfo
     *
     * Get receipts address resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchAddressResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchAddressResolutionStatementsAsyncWithHttpInfo($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchAddressResolutionStatements'][0])
    {
        $returnType = '\SymbolRestClient\Model\ResolutionStatementPage';
        $request = $this->searchAddressResolutionStatementsRequest($height, $page_size, $page_number, $offset, $order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchAddressResolutionStatements'
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchAddressResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchAddressResolutionStatementsRequest($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchAddressResolutionStatements'][0])
    {


        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchAddressResolutionStatements, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 10) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchAddressResolutionStatements, must be bigger than or equal to 10.');
        }
        
        if ($page_number !== null && $page_number < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ReceiptRoutesApi.searchAddressResolutionStatements, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/statements/resolutions/address';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $height,
            'height', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'Order', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchMosaicResolutionStatements
     *
     * Get receipts mosaic resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMosaicResolutionStatements'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SymbolRestClient\Model\ResolutionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError
     */
    public function searchMosaicResolutionStatements($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchMosaicResolutionStatements'][0])
    {
        list($response) = $this->searchMosaicResolutionStatementsWithHttpInfo($height, $page_size, $page_number, $offset, $order, $contentType);
        return $response;
    }

    /**
     * Operation searchMosaicResolutionStatementsWithHttpInfo
     *
     * Get receipts mosaic resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMosaicResolutionStatements'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SymbolRestClient\Model\ResolutionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchMosaicResolutionStatementsWithHttpInfo($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchMosaicResolutionStatements'][0])
    {
        $request = $this->searchMosaicResolutionStatementsRequest($height, $page_size, $page_number, $offset, $order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SymbolRestClient\Model\ResolutionStatementPage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ResolutionStatementPage' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ResolutionStatementPage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SymbolRestClient\Model\ResolutionStatementPage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ResolutionStatementPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchMosaicResolutionStatementsAsync
     *
     * Get receipts mosaic resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMosaicResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMosaicResolutionStatementsAsync($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchMosaicResolutionStatements'][0])
    {
        return $this->searchMosaicResolutionStatementsAsyncWithHttpInfo($height, $page_size, $page_number, $offset, $order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchMosaicResolutionStatementsAsyncWithHttpInfo
     *
     * Get receipts mosaic resolution statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMosaicResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMosaicResolutionStatementsAsyncWithHttpInfo($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchMosaicResolutionStatements'][0])
    {
        $returnType = '\SymbolRestClient\Model\ResolutionStatementPage';
        $request = $this->searchMosaicResolutionStatementsRequest($height, $page_size, $page_number, $offset, $order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchMosaicResolutionStatements'
     *
     * @param  string $height Filter by block height. (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMosaicResolutionStatements'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchMosaicResolutionStatementsRequest($height = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchMosaicResolutionStatements'][0])
    {


        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchMosaicResolutionStatements, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 10) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchMosaicResolutionStatements, must be bigger than or equal to 10.');
        }
        
        if ($page_number !== null && $page_number < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ReceiptRoutesApi.searchMosaicResolutionStatements, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/statements/resolutions/mosaic';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $height,
            'height', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'Order', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchReceipts
     *
     * Search transaction statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  string $from_height Only blocks with height greater or equal than this one are returned. (optional)
     * @param  string $to_height Only blocks with height smaller or equal than this one are returned. (optional)
     * @param  \SymbolRestClient\Model\ReceiptTypeEnum[] $receipt_type Filter by receipt type. To filter by multiple receipt types, add more filter query params like: &#x60;&#x60;receiptType&#x3D;8515&amp;receiptType&#x3D;20803&#x60;&#x60;. (optional)
     * @param  string $recipient_address Filter by address of the account receiving the transaction. (optional)
     * @param  string $sender_address Filter by address sending mosaics. (optional)
     * @param  string $target_address Filter by target address. (optional)
     * @param  string $artifact_id Mosaic or namespace identifier (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchReceipts'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SymbolRestClient\Model\TransactionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError
     */
    public function searchReceipts($height = null, $from_height = null, $to_height = null, $receipt_type = null, $recipient_address = null, $sender_address = null, $target_address = null, $artifact_id = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchReceipts'][0])
    {
        list($response) = $this->searchReceiptsWithHttpInfo($height, $from_height, $to_height, $receipt_type, $recipient_address, $sender_address, $target_address, $artifact_id, $page_size, $page_number, $offset, $order, $contentType);
        return $response;
    }

    /**
     * Operation searchReceiptsWithHttpInfo
     *
     * Search transaction statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  string $from_height Only blocks with height greater or equal than this one are returned. (optional)
     * @param  string $to_height Only blocks with height smaller or equal than this one are returned. (optional)
     * @param  \SymbolRestClient\Model\ReceiptTypeEnum[] $receipt_type Filter by receipt type. To filter by multiple receipt types, add more filter query params like: &#x60;&#x60;receiptType&#x3D;8515&amp;receiptType&#x3D;20803&#x60;&#x60;. (optional)
     * @param  string $recipient_address Filter by address of the account receiving the transaction. (optional)
     * @param  string $sender_address Filter by address sending mosaics. (optional)
     * @param  string $target_address Filter by target address. (optional)
     * @param  string $artifact_id Mosaic or namespace identifier (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchReceipts'] to see the possible values for this operation
     *
     * @throws \SymbolRestClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SymbolRestClient\Model\TransactionStatementPage|\SymbolRestClient\Model\ModelError|\SymbolRestClient\Model\ModelError, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchReceiptsWithHttpInfo($height = null, $from_height = null, $to_height = null, $receipt_type = null, $recipient_address = null, $sender_address = null, $target_address = null, $artifact_id = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchReceipts'][0])
    {
        $request = $this->searchReceiptsRequest($height, $from_height, $to_height, $receipt_type, $recipient_address, $sender_address, $target_address, $artifact_id, $page_size, $page_number, $offset, $order, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SymbolRestClient\Model\TransactionStatementPage' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\TransactionStatementPage' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\TransactionStatementPage', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 409:
                    if ('\SymbolRestClient\Model\ModelError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SymbolRestClient\Model\ModelError' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SymbolRestClient\Model\ModelError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SymbolRestClient\Model\TransactionStatementPage';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\TransactionStatementPage',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SymbolRestClient\Model\ModelError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation searchReceiptsAsync
     *
     * Search transaction statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  string $from_height Only blocks with height greater or equal than this one are returned. (optional)
     * @param  string $to_height Only blocks with height smaller or equal than this one are returned. (optional)
     * @param  \SymbolRestClient\Model\ReceiptTypeEnum[] $receipt_type Filter by receipt type. To filter by multiple receipt types, add more filter query params like: &#x60;&#x60;receiptType&#x3D;8515&amp;receiptType&#x3D;20803&#x60;&#x60;. (optional)
     * @param  string $recipient_address Filter by address of the account receiving the transaction. (optional)
     * @param  string $sender_address Filter by address sending mosaics. (optional)
     * @param  string $target_address Filter by target address. (optional)
     * @param  string $artifact_id Mosaic or namespace identifier (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchReceiptsAsync($height = null, $from_height = null, $to_height = null, $receipt_type = null, $recipient_address = null, $sender_address = null, $target_address = null, $artifact_id = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchReceipts'][0])
    {
        return $this->searchReceiptsAsyncWithHttpInfo($height, $from_height, $to_height, $receipt_type, $recipient_address, $sender_address, $target_address, $artifact_id, $page_size, $page_number, $offset, $order, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchReceiptsAsyncWithHttpInfo
     *
     * Search transaction statements
     *
     * @param  string $height Filter by block height. (optional)
     * @param  string $from_height Only blocks with height greater or equal than this one are returned. (optional)
     * @param  string $to_height Only blocks with height smaller or equal than this one are returned. (optional)
     * @param  \SymbolRestClient\Model\ReceiptTypeEnum[] $receipt_type Filter by receipt type. To filter by multiple receipt types, add more filter query params like: &#x60;&#x60;receiptType&#x3D;8515&amp;receiptType&#x3D;20803&#x60;&#x60;. (optional)
     * @param  string $recipient_address Filter by address of the account receiving the transaction. (optional)
     * @param  string $sender_address Filter by address sending mosaics. (optional)
     * @param  string $target_address Filter by target address. (optional)
     * @param  string $artifact_id Mosaic or namespace identifier (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchReceiptsAsyncWithHttpInfo($height = null, $from_height = null, $to_height = null, $receipt_type = null, $recipient_address = null, $sender_address = null, $target_address = null, $artifact_id = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchReceipts'][0])
    {
        $returnType = '\SymbolRestClient\Model\TransactionStatementPage';
        $request = $this->searchReceiptsRequest($height, $from_height, $to_height, $receipt_type, $recipient_address, $sender_address, $target_address, $artifact_id, $page_size, $page_number, $offset, $order, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchReceipts'
     *
     * @param  string $height Filter by block height. (optional)
     * @param  string $from_height Only blocks with height greater or equal than this one are returned. (optional)
     * @param  string $to_height Only blocks with height smaller or equal than this one are returned. (optional)
     * @param  \SymbolRestClient\Model\ReceiptTypeEnum[] $receipt_type Filter by receipt type. To filter by multiple receipt types, add more filter query params like: &#x60;&#x60;receiptType&#x3D;8515&amp;receiptType&#x3D;20803&#x60;&#x60;. (optional)
     * @param  string $recipient_address Filter by address of the account receiving the transaction. (optional)
     * @param  string $sender_address Filter by address sending mosaics. (optional)
     * @param  string $target_address Filter by target address. (optional)
     * @param  string $artifact_id Mosaic or namespace identifier (optional)
     * @param  int $page_size Select the number of entries to return. (optional, default to 10)
     * @param  int $page_number Filter by page number. (optional, default to 1)
     * @param  string $offset Entry id at which to start pagination. If the ordering parameter is set to -id, the elements returned precede the identifier. Otherwise, newer elements with respect to the id are returned. (optional)
     * @param  Order $order Sort responses in ascending or descending order based on the collection property set on the param &#x60;&#x60;orderBy&#x60;&#x60;. If the request does not specify &#x60;&#x60;orderBy&#x60;&#x60;, REST returns the collection ordered by id. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchReceipts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchReceiptsRequest($height = null, $from_height = null, $to_height = null, $receipt_type = null, $recipient_address = null, $sender_address = null, $target_address = null, $artifact_id = null, $page_size = 10, $page_number = 1, $offset = null, $order = null, string $contentType = self::contentTypes['searchReceipts'][0])
    {









        if ($page_size !== null && $page_size > 100) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchReceipts, must be smaller than or equal to 100.');
        }
        if ($page_size !== null && $page_size < 10) {
            throw new \InvalidArgumentException('invalid value for "$page_size" when calling ReceiptRoutesApi.searchReceipts, must be bigger than or equal to 10.');
        }
        
        if ($page_number !== null && $page_number < 1) {
            throw new \InvalidArgumentException('invalid value for "$page_number" when calling ReceiptRoutesApi.searchReceipts, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/statements/transaction';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $height,
            'height', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from_height,
            'fromHeight', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $to_height,
            'toHeight', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $receipt_type,
            'receiptType', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $recipient_address,
            'recipientAddress', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sender_address,
            'senderAddress', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $target_address,
            'targetAddress', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $artifact_id,
            'artifactId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order,
            'order', // param base name
            'Order', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
