/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing AccountAddressRestrictionTransactionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountAddressRestrictionTransactionDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountAddressRestrictionTransactionDTO
        //private AccountAddressRestrictionTransactionDTO instance;

        public AccountAddressRestrictionTransactionDTOTests()
        {
            // TODO uncomment below to create an instance of AccountAddressRestrictionTransactionDTO
            //instance = new AccountAddressRestrictionTransactionDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountAddressRestrictionTransactionDTO
        /// </summary>
        [Fact]
        public void AccountAddressRestrictionTransactionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountAddressRestrictionTransactionDTO
            //Assert.IsType<AccountAddressRestrictionTransactionDTO>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

        /// <summary>
        /// Test the property 'SignerPublicKey'
        /// </summary>
        [Fact]
        public void SignerPublicKeyTest()
        {
            // TODO unit test for the property 'SignerPublicKey'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'MaxFee'
        /// </summary>
        [Fact]
        public void MaxFeeTest()
        {
            // TODO unit test for the property 'MaxFee'
        }

        /// <summary>
        /// Test the property 'Deadline'
        /// </summary>
        [Fact]
        public void DeadlineTest()
        {
            // TODO unit test for the property 'Deadline'
        }

        /// <summary>
        /// Test the property 'RestrictionFlags'
        /// </summary>
        [Fact]
        public void RestrictionFlagsTest()
        {
            // TODO unit test for the property 'RestrictionFlags'
        }

        /// <summary>
        /// Test the property 'RestrictionAdditions'
        /// </summary>
        [Fact]
        public void RestrictionAdditionsTest()
        {
            // TODO unit test for the property 'RestrictionAdditions'
        }

        /// <summary>
        /// Test the property 'RestrictionDeletions'
        /// </summary>
        [Fact]
        public void RestrictionDeletionsTest()
        {
            // TODO unit test for the property 'RestrictionDeletions'
        }
    }
}
