/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EmbeddedAccountAddressRestrictionTransactionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EmbeddedAccountAddressRestrictionTransactionDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EmbeddedAccountAddressRestrictionTransactionDTO
        //private EmbeddedAccountAddressRestrictionTransactionDTO instance;

        public EmbeddedAccountAddressRestrictionTransactionDTOTests()
        {
            // TODO uncomment below to create an instance of EmbeddedAccountAddressRestrictionTransactionDTO
            //instance = new EmbeddedAccountAddressRestrictionTransactionDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EmbeddedAccountAddressRestrictionTransactionDTO
        /// </summary>
        [Fact]
        public void EmbeddedAccountAddressRestrictionTransactionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" EmbeddedAccountAddressRestrictionTransactionDTO
            //Assert.IsType<EmbeddedAccountAddressRestrictionTransactionDTO>(instance);
        }

        /// <summary>
        /// Test the property 'SignerPublicKey'
        /// </summary>
        [Fact]
        public void SignerPublicKeyTest()
        {
            // TODO unit test for the property 'SignerPublicKey'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Network'
        /// </summary>
        [Fact]
        public void NetworkTest()
        {
            // TODO unit test for the property 'Network'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'RestrictionFlags'
        /// </summary>
        [Fact]
        public void RestrictionFlagsTest()
        {
            // TODO unit test for the property 'RestrictionFlags'
        }

        /// <summary>
        /// Test the property 'RestrictionAdditions'
        /// </summary>
        [Fact]
        public void RestrictionAdditionsTest()
        {
            // TODO unit test for the property 'RestrictionAdditions'
        }

        /// <summary>
        /// Test the property 'RestrictionDeletions'
        /// </summary>
        [Fact]
        public void RestrictionDeletionsTest()
        {
            // TODO unit test for the property 'RestrictionDeletions'
        }
    }
}
