/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InflationReceiptDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InflationReceiptDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InflationReceiptDTO
        //private InflationReceiptDTO instance;

        public InflationReceiptDTOTests()
        {
            // TODO uncomment below to create an instance of InflationReceiptDTO
            //instance = new InflationReceiptDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InflationReceiptDTO
        /// </summary>
        [Fact]
        public void InflationReceiptDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" InflationReceiptDTO
            //Assert.IsType<InflationReceiptDTO>(instance);
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'MosaicId'
        /// </summary>
        [Fact]
        public void MosaicIdTest()
        {
            // TODO unit test for the property 'MosaicId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
    }
}
