/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LinkActionEnum
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LinkActionEnumTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LinkActionEnum
        //private LinkActionEnum instance;

        public LinkActionEnumTests()
        {
            // TODO uncomment below to create an instance of LinkActionEnum
            //instance = new LinkActionEnum();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LinkActionEnum
        /// </summary>
        [Fact]
        public void LinkActionEnumInstanceTest()
        {
            // TODO uncomment below to test "IsType" LinkActionEnum
            //Assert.IsType<LinkActionEnum>(instance);
        }
    }
}
