/*
 * Catapult REST Endpoints
 *
 * OpenAPI Specification of catapult-rest
 *
 * The version of the OpenAPI document: 1.0.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SecretProofTransactionBodyDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SecretProofTransactionBodyDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SecretProofTransactionBodyDTO
        //private SecretProofTransactionBodyDTO instance;

        public SecretProofTransactionBodyDTOTests()
        {
            // TODO uncomment below to create an instance of SecretProofTransactionBodyDTO
            //instance = new SecretProofTransactionBodyDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SecretProofTransactionBodyDTO
        /// </summary>
        [Fact]
        public void SecretProofTransactionBodyDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SecretProofTransactionBodyDTO
            //Assert.IsType<SecretProofTransactionBodyDTO>(instance);
        }

        /// <summary>
        /// Test the property 'RecipientAddress'
        /// </summary>
        [Fact]
        public void RecipientAddressTest()
        {
            // TODO unit test for the property 'RecipientAddress'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }

        /// <summary>
        /// Test the property 'HashAlgorithm'
        /// </summary>
        [Fact]
        public void HashAlgorithmTest()
        {
            // TODO unit test for the property 'HashAlgorithm'
        }

        /// <summary>
        /// Test the property 'Proof'
        /// </summary>
        [Fact]
        public void ProofTest()
        {
            // TODO unit test for the property 'Proof'
        }
    }
}
