/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param publicKeys Array of public keys.
 * @param addresses Array of addresses.
 */


data class AccountIds (

    /* Array of public keys. */
    @Json(name = "publicKeys")
    val publicKeys: kotlin.collections.List<kotlin.String>? = null,

    /* Array of addresses. */
    @Json(name = "addresses")
    val addresses: kotlin.collections.List<kotlin.String>? = null

)

