//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.12

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openapi/api.dart';
import 'package:test/test.dart';

// tests for AccountAddressRestrictionTransactionDTO
void main() {
  // final instance = AccountAddressRestrictionTransactionDTO();

  group('test AccountAddressRestrictionTransactionDTO', () {
    // A number that allows uint 32 values.
    // int size
    test('to test the property `size`', () async {
      // TODO
    });

    // Entity's signature generated by the signer.
    // String signature
    test('to test the property `signature`', () async {
      // TODO
    });

    // Public key.
    // String signerPublicKey
    test('to test the property `signerPublicKey`', () async {
      // TODO
    });

    // Entity version.
    // int version
    test('to test the property `version`', () async {
      // TODO
    });

    // NetworkTypeEnum network
    test('to test the property `network`', () async {
      // TODO
    });

    // int type
    test('to test the property `type`', () async {
      // TODO
    });

    // Absolute amount. An amount of 123456789 (absolute) for a mosaic with divisibility 6 means 123.456789 (relative).
    // String maxFee
    test('to test the property `maxFee`', () async {
      // TODO
    });

    // Duration expressed in number of blocks.
    // String deadline
    test('to test the property `deadline`', () async {
      // TODO
    });

    // AccountRestrictionFlagsEnum restrictionFlags
    test('to test the property `restrictionFlags`', () async {
      // TODO
    });

    // Account restriction additions.
    // List<String> restrictionAdditions (default value: const [])
    test('to test the property `restrictionAdditions`', () async {
      // TODO
    });

    // Account restriction deletions.
    // List<String> restrictionDeletions (default value: const [])
    test('to test the property `restrictionDeletions`', () async {
      // TODO
    });


  });

}
